In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [8]:
#reading the file and exploring it 
data = pd.read_csv("data_titanic_2.csv")
data.head()

Embarked_Q  Embarked_S  Sex_male  Parch_1  Parch_2  Parch_3  Parch_4  \
0           0           1         1        0        0        0        0   
1           0           0         0        0        0        0        0   
2           0           1         0        0        0        0        0   
3           0           1         0        0        0        0        0   
4           0           1         1        0        0        0        0   

   Parch_5  Parch_6  SibSp_1  ...  SibSp_3  SibSp_4  SibSp_5  SibSp_8  \
0        0        0        1  ...        0        0        0        0   
1        0        0        1  ...        0        0        0        0   
2        0        0        0  ...        0        0        0        0   
3        0        0        1  ...        0        0        0        0   
4        0        0        0  ...        0        0        0        0   

   Pclass_2  Pclass_3  Age_(21.0, 30.0]  Age_(30.0, 35.0]  Age_(35.0, 80.0]  \
0         0         1                 1                 0                 0   
1         0         0                 0                 0                 1   
2         0         1                 1                 0                 0   
3         0         0                 0                 1                 0   
4         0         1                 0                 1                 0   

   Survived  
0         0  
1         1  
2         1  
3         1  
4         0  

[5 rows x 21 columns]

In [7]:
data.shape

(891, 12)

In [9]:
data.describe()

Embarked_Q  Embarked_S    Sex_male     Parch_1     Parch_2     Parch_3  \
count  889.000000  889.000000  889.000000  889.000000  889.000000  889.000000   
mean     0.086614    0.724409    0.649044    0.132733    0.089989    0.005624   
std      0.281427    0.447063    0.477538    0.339477    0.286327    0.074826   
min      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.000000    0.000000    0.000000    0.000000    0.000000    0.000000   
50%      0.000000    1.000000    1.000000    0.000000    0.000000    0.000000   
75%      0.000000    1.000000    1.000000    0.000000    0.000000    0.000000   
max      1.000000    1.000000    1.000000    1.000000    1.000000    1.000000   

          Parch_4     Parch_5     Parch_6     SibSp_1  ...     SibSp_3  \
count  889.000000  889.000000  889.000000  889.000000  ...  889.000000   
mean     0.004499    0.005624    0.001125    0.235096  ...    0.017998   
std      0.066964    0.074826    0.033539    0.424297  ...    0.133018   
min      0.000000    0.000000    0.000000    0.000000  ...    0.000000   
25%      0.000000    0.000000    0.000000    0.000000  ...    0.000000   
50%      0.000000    0.000000    0.000000    0.000000  ...    0.000000   
75%      0.000000    0.000000    0.000000    0.000000  ...    0.000000   
max      1.000000    1.000000    1.000000    1.000000  ...    1.000000   

          SibSp_4     SibSp_5     SibSp_8    Pclass_2    Pclass_3  \
count  889.000000  889.000000  889.000000  889.000000  889.000000   
mean     0.020247    0.005624    0.007874    0.206974    0.552306   
std      0.140925    0.074826    0.088435    0.405365    0.497536   
min      0.000000    0.000000    0.000000    0.000000    0.000000   
25%      0.000000    0.000000    0.000000    0.000000    0.000000   
50%      0.000000    0.000000    0.000000    0.000000    1.000000   
75%      0.000000    0.000000    0.000000    0.000000    1.000000   
max      1.000000    1.000000    1.000000    1.000000    1.000000   

       Age_(21.0, 30.0]  Age_(30.0, 35.0]  Age_(35.0, 80.0]    Survived  
count        889.000000        889.000000        889.000000  889.000000  
mean           0.383577          0.098988          0.241845    0.382452  
std            0.486531          0.298814          0.428442    0.486260  
min            0.000000          0.000000          0.000000    0.000000  
25%            0.000000          0.000000          0.000000    0.000000  
50%            0.000000          0.000000          0.000000    0.000000  
75%            1.000000          0.000000          0.000000    1.000000  
max            1.000000          1.000000          1.000000    1.000000  

[8 rows x 21 columns]



### Part 1 Logistic Regression

1. Apply logistic regression. 

2. Use confusion matrix to validate your model. 

3. Another validation matrix for classification is ROC / AUC , do your research on them explain them and apply them in our case

In [27]:
from sklearn.linear_model import LogisticRegression # modele 
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix,accuracy_score # for testing performance 

In [28]:
cols =  list(data.keys())
cols.pop()
x = data[cols]
y = data.Survived # target

cols



['Embarked_Q',
 'Embarked_S',
 'Sex_male',
 'Parch_1',
 'Parch_2',
 'Parch_3',
 'Parch_4',
 'Parch_5',
 'Parch_6',
 'SibSp_1',
 'SibSp_2',
 'SibSp_3',
 'SibSp_4',
 'SibSp_5',
 'SibSp_8',
 'Pclass_2',
 'Pclass_3',
 'Age_(21.0, 30.0]',
 'Age_(30.0, 35.0]',
 'Age_(35.0, 80.0]']

In [29]:
# spliting the data 
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=0) 

model = LogisticRegression()  

model.fit(x_train,y_train) 

LogisticRegression()

In [30]:
y_pred = model.predict(x_test)
y_pred

array([1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1,
       1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1,
       1, 0, 1])

In [31]:
accuracy_score(y_pred, y_test)

0.7623318385650224

In [32]:
confusion_matrix(y_pred, y_test)

array([[114,  35],
       [ 18,  56]])

In [33]:
classification_report(y_pred,y_test)

'              precision    recall  f1-score   support\n\n           0       0.86      0.77      0.81       149\n           1       0.62      0.76      0.68        74\n\n    accuracy                           0.76       223\n   macro avg       0.74      0.76      0.75       223\nweighted avg       0.78      0.76      0.77       223\n'

# KNN

In [34]:
from sklearn.neighbors import NearestNeighbors
from sklearn.neighbors import KNeighborsClassifier

In [54]:
data = pd.read_csv("titanic.csv")
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [51]:
data.shape

(891, 12)

In [62]:
data.describe()

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  891.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.361582    0.523008   
std     257.353842    0.486592    0.836071   13.019697    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   22.000000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   35.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch      Family  
count  891.000000  891.000000  
mean     0.381594    1.904602  
std      0.806057    1.613459  
min      0.000000    1.000000  
25%      0.000000    1.000000  
50%      0.000000    1.000000  
75%      0.000000    2.000000  
max      6.000000   11.000000

In [61]:
data.isnull()

PassengerId  Survived  Pclass    Sex    Age  SibSp  Parch  Embarked  \
0          False     False   False  False  False  False  False     False   
1          False     False   False  False  False  False  False     False   
2          False     False   False  False  False  False  False     False   
3          False     False   False  False  False  False  False     False   
4          False     False   False  False  False  False  False     False   
..           ...       ...     ...    ...    ...    ...    ...       ...   
886        False     False   False  False  False  False  False     False   
887        False     False   False  False  False  False  False     False   
888        False     False   False  False  False  False  False     False   
889        False     False   False  False  False  False  False     False   
890        False     False   False  False  False  False  False     False   

     Family  
0     False  
1     False  
2     False  
3     False  
4     False  
..      ...  
886   False  
887   False  
888   False  
889   False  
890   False  

[891 rows x 9 columns]

In [55]:
#cleaning the data set 
data = data.drop('Name', axis=1,)
data = data.drop('Ticket', axis=1,)
data = data.drop('Fare', axis=1,)
data = data.drop('Cabin', axis=1,)
data['Family'] = data['SibSp'] + data['Parch'] + 1

In [57]:
data["Age"] = data["Age"].fillna(data["Age"].median())

In [58]:
data['Embarked'].value_counts()


S    644
C    168
Q     77
Name: Embarked, dtype: int64

In [59]:
print(data["Embarked"].mode())


0    S
Name: Embarked, dtype: object


In [60]:
data["Embarked"] = data["Embarked"].fillna("S")

In [63]:
data["Embarked"].unique()


array(['S', 'C', 'Q'], dtype=object)

In [64]:
data.Embarked.replace(['S', 'C', 'Q'], [1, 2, 3], inplace=True)


In [65]:
data.Sex.replace(['male', 'female'], [1,0], inplace=True)

In [71]:
data.isnull()

PassengerId  Survived  Pclass    Sex    Age  SibSp  Parch  Embarked  \
0          False     False   False  False  False  False  False     False   
1          False     False   False  False  False  False  False     False   
2          False     False   False  False  False  False  False     False   
3          False     False   False  False  False  False  False     False   
4          False     False   False  False  False  False  False     False   
..           ...       ...     ...    ...    ...    ...    ...       ...   
886        False     False   False  False  False  False  False     False   
887        False     False   False  False  False  False  False     False   
888        False     False   False  False  False  False  False     False   
889        False     False   False  False  False  False  False     False   
890        False     False   False  False  False  False  False     False   

     Family  
0     False  
1     False  
2     False  
3     False  
4     False  
..      ...  
886   False  
887   False  
888   False  
889   False  
890   False  

[891 rows x 9 columns]

In [66]:
y = np.array(data.filter(['Survived'], axis=1))
X=np.array(data.filter(['Pclass','Sex','Embarked','Family','Age'], axis=1))

In [75]:
X_1, X_test, y_1, y_test = train_test_split(X,y, test_size=0.3)


In [77]:

knn = KNeighborsClassifier(n_neighbors = 10)
knn.fit(X_1, y_1)
pred = knn.predict(X_test)
confusion_matrix(pred,y_test)
#classification_report(pred,y_cv)

/home/ahmed/anaconda3/lib/python3.9/site-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
/home/ahmed/anaconda3/lib/python3.9/site-packages/sklearn/neighbors/_classification.py:228: FutureWarning: Unlike other reduction functions (e.g. `skew`, `kurtosis`), the default behavior of `mode` typically preserves the axis it acts along. In SciPy 1.11.0, this behavior will change: the default value of `keepdims` will become False, the `axis` over which the statistic is taken will be eliminated, and the value None will no longer be accepted. Set `keepdims` to True or False to avoid this warning.
  mode, _ = stats.mode(_y[neigh_ind, k], axis=1)


array([[156,  44],
       [ 17,  51]])